Feature/mobile/343 dev
Papinotas-Desarrollo/phoenix-mobile-toolbox pull request #10
Opened 2019-05-23 21:53 UTC by tomasmedina

- Added `HelpAccordion` component.
- Added functions to call and send email to Papinotas Support team
- iOS added handling for choosing different email clients by checking if they are installed or not (Android handles this automatically so there was no need for an implementation)
- Updated `ErrorBoundary` component to also call or send an email to Support. In this case the email also contains the error object

2019-05-24 13:57 UTC, ccanalesb requested changes

2019-05-24 13:57 UTC, ccanalesb commented on src/components/Help/HelpAccordion.js
> +        onPress: () => console.log('CANCEL: Email Error Response'),
creo que a nivel toolbox, la acción de este onPress deberia pasar como un prop, asi se puede modificar y llamar a lo que sea

2019-05-24 13:57 UTC, ccanalesb commented on src/components/Help/HelpAccordion.js
> +          console.log('error');
Lo mismo acá, la acción del error debería ser un props, o por defecto un console log

2019-05-24 13:57 UTC, ccanalesb commented on src/components/Help/HelpAccordion.js
> +export const sendEmail = async (
este componente debería estar en otro archivo

2019-05-24 13:57 UTC, ccanalesb commented on src/components/Help/HelpAccordion.js
> +checkApp = emailBody =>
esta función deberia ser llamado desde otro archivo

2019-05-24 13:57 UTC, ccanalesb commented on src/components/Help/HelpAccordion.js
> +        sendEmail(appVersion, phone, osVersion, currentAccount);
La función sendEmail deberia ser un prop también. La idea detrás de esto es que toolbox es solo un conjunto de formas de visualizar, y la logica y la información que se muestra se la tienes que pasar tu.
Por ejemplo, si en familia queremos cierta información, en Comunicaciones nos interesa otra, podemos cambiar la función que muestra la información a nuestro antojo de acuerdo a las necesidades del proyecto

2019-05-24 13:57 UTC, ccanalesb commented on src/components/Help/HelpAccordion.js
> +
falta agregar como se usa

2019-05-24 18:10 UTC, tomasmedina commented on src/components/Help/HelpAccordion.js
> +        onPress: () => console.log('CANCEL: Email Error Response'),
La acción del `OnPress` al cancelar la alerta?

2019-05-24 18:17 UTC, tomasmedina commented on src/components/Help/HelpAccordion.js
> +export const sendEmail = async (
por qué si es una función? no retorna un componente, retorna un objeto

2019-05-24 18:34 UTC, tomasmedina commented on src/components/Help/HelpAccordion.js
> +        sendEmail(appVersion, phone, osVersion, currentAccount);
no estoy de acuerdo, por que si fuese así entonces también tendría que pasar por props los botones que llegan al `ErrorView` ya que esos también podrían cambiar y podrían ser otras cosas que no fueran enviar correo o llamar por teléfono.
Si ese es el caso entonces lo cambio pero para eso entonces tendría que manejar casi todas las funciones que estoy pasando fuera de toolbox y eso consideraría duplicación de código en ambas apps.

2019-05-24 18:40 UTC, ccanalesb commented on src/components/Help/HelpAccordion.js
> +        onPress: () => console.log('CANCEL: Email Error Response'),
Sip

2019-05-26 22:09 UTC, ccanalesb approved these changes

2019-05-27 15:14 UTC, merged