maintenance/mobile/2719
Papinotas-Desarrollo/phoenix-mobile-toolbox pull request #48
Opened 2020-05-08 15:37 UTC by JulioOrellana

* Fix scroll bug by styles

2020-05-08 15:40 UTC, ccanalesb requested changes

2020-05-08 15:40 UTC, ccanalesb commented on src/components/SideMenu/___test___/SideMenuScreen.test.js
>    });
Agregar un test de scroll, que al agregar varios hijos, donde al scrolear se puedan seguir apretando los items

2020-05-08 15:42 UTC, JulioOrellana commented on src/components/SideMenu/___test___/SideMenuScreen.test.js
>    });
Pero eso sería un test de integración con el accordion, el menú es solamente para mostrar, ese test tiene que hacerse en el componente armado, en lam app familia

2020-05-08 15:44 UTC, ccanalesb commented on src/components/SideMenu/___test___/SideMenuScreen.test.js
>    });
No es un test de integración, esto debería testear que se pueden renderear cosas.
Acá estas intentando arreglar un bug de scroll, y no lo estas demostrando en test.

2020-05-08 15:54 UTC, JulioOrellana commented on src/components/SideMenu/___test___/SideMenuScreen.test.js
>    });
El bug se genera en como se estaba renderando este item en el menú de la app familia, además era un problema con el `safeArea de react-native`, aproveché de mover otras cosas acá ya que necesitaba sacar el safeArea y eliminar unos props que ya no se necesitaban.

2020-05-08 16:02 UTC, ccanalesb commented on src/components/SideMenu/___test___/SideMenuScreen.test.js
>    });
Si, pero igual veo necesario el test

2020-05-08 16:03 UTC, JulioOrellana commented on src/components/SideMenu/___test___/SideMenuScreen.test.js
>    });
No tengo como demostrar ni rehacer el "bug" desde acá

2020-05-08 16:03 UTC, JulioOrellana commented on src/components/SideMenu/___test___/SideMenuScreen.test.js
>    });
ok

2020-05-11 18:57 UTC, ccanalesb approved these changes

2020-05-11 19:21 UTC, merged